export default [
  {
    name: "Casa Padrino Luxury Baroque Decorative Vase White",
    description: "Sophisticated vessel for decorative branches and dried flowers.",
    price: 1500.0,
    image_name: "https://cdn02.plentymarkets.com/vji7b8phcm0f/item/images/123900/full/Casa-Padrino-Barock-Deko-Vase-Beige---Mehrfarbig---Gold-21-1-x-17-7-x-H--48-2-cm-Prunkvolle-Porzellan-Blumenvase-mit-edlen-Bronzefiguren-Deko-Accessoires-im-Barockstil-123900_1.JPG",
    createdAt: new Date(),
  },
  {
    name: "Floor Vase ATRIUM",
    description: "Atelier Edition 2022.",
    price: 4900.0,
    image_name: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRXUtIKZ3qZQZ2YiVdWo7umZrMI3RLr6DV_u86TT85CdEExJ_ViOrBRmHqyLh2fjadu5OV49kTF8-lpUEXK5QyhRxMOyHu9o-0zhIH4ypswLockvhbaRS52L5m3V617hw&usqp=CAc",
    createdAt: new Date(),
  },
  {
    name: "Porcelain Cobalt Vase",
    description: "Porcelain Cobalt Vase from Hutschenreuther Hohenberg, Germany, 1960s.",
    price: 200.0,
    image_name: "https://cdn20.pamono.com/p/m/1/4/1458963_z7pvzrrwhl/porcelain-cobalt-vase-from-hutschenreuther-hohenberg-germany-1960s.jpg",
    createdAt: new Date(),
  },
  {
    name: "Art Nouveau Vases",
    description: "Art Nouveau Vases from Royal Limoges, Set of 2.",
    price: 1700.0,
    image_name: "https://cdn20.pamono.com/p/g/7/2/72487_6lXl8M2Ui1/art-nouveau-vases-from-royal-limoges-set-of-2-1.jpg",
    createdAt: new Date(),
  },
  {
    name: "Blue Chevron Crystal Vase",
    description: "A blue crystal vase with a hand-engraved chevron pattern.",
    price: 1500.0,
    image_name: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRUqHklVIIEOwewrJXEN4rtlALjOG2QxOFD3Vw6rDzMd2M313j2o6COvhkT--4Yo9uzKFj8ZhttDSdO9cL0vBYIwcYADs6a3S_pDlPiemueaYgyZJFyj7b9wnmD-T-xrhs-LYno5Jw2&usqp=CAc",
    createdAt: new Date(),
  },
  {
    name: "Diamond Faceted Green Glass Vase And Bowl",
    description: "Handcrafted, detailed ornate brass structure in a shiny Gold finish.",
    price: 3161.0,
    image_name: "https://www.juliettesinteriors.co.uk/wp-content/uploads/2023/06/diamond-faceted-green-glass-vases-1-2-534x534.jpg",
    createdAt: new Date(),
  },
  {
    name: "Ornate Jewelled Glass Centrepiece and Vase",
    description: "Expertly handcrafted in unmistakably high-quality hand-blown glass.",
    price: 1888.0,
    image_name: "https://www.juliettesinteriors.co.uk/wp-content/uploads/2023/07/ornate-jewelled-glass-centrepiece-and-vase-1-364x364.jpg",
    createdAt: new Date(),
  },
  {
    name: "Luxury Amethyst Glass Vase And Bowl",
    description: "Expertly handcrafted in high-quality hand-blown glass.",
    price: 1255.0,
    image_name: "https://www.juliettesinteriors.co.uk/wp-content/uploads/2023/07/luxury-amethyst-glass-vase-3-534x534.jpg",
    createdAt: new Date(),
  },
  {
    name: "Almeta Brown & Champagne Metal & Glass Gold Vase",
    description: "Combines functionality with lustre and luxury.",
    price: 9990.0,
    image_name: "https://addresshome.com/cdn/shop/files/AH17901f_700x.jpg?v=1727498321",
    createdAt: new Date(),
  },
  {
    name: "Vase Tourbillons",
    description: "H20,8 cm, ø 20 cm, 6,7 kg. Hand-cut crystal glass, partially satined.",
    price: 4500.0,
    image_name: "https://src.artedona.com/generated/product/1/_DPx1/1719320487~75080_1.jpg",
    createdAt: new Date(),
  },
  {
    name: "Royal-Style Luxury Ceramic Vase",
    description: "Royal-Style Luxury Ceramic Vase with its body color in pristine white and a mesmerizing gold finish, is the epitome of luxury and sophistication.",
    price: 41100.0,
    image_name: "https://www.lighttrybe.ng/wp-content/uploads/2022/01/2021-European-Style-Golden-Luxury-Ceramic-Vase-Ornaments-Dry-Flower-Living-Room-Modern-Simple-Vases-Home.jpg",
    createdAt: new Date(),
  },
  {
    name: "Qianlong period vase",
    description: "A beautifully detailed ornate brass structure in a French Gold satin finish.",
    price: 186000.0,
    image_name: "https://media.cnn.com/api/v1/images/stellar/prod/220505083505-02-qianlong-dynasty-vase-kitchen.jpg?c=original",
    createdAt: new Date(),
  },
];